// 中文原文 → 英文。以中文原文作为 key，缺失项自动回退为中文（不会出现空白 UI）。
// 全软件中英覆盖：每批转换时把该批文案补进这里。
export const zhEn: Record<string, string> = {
  // —— 应用外壳 / chrome ——
  '对话': 'Chat',
  '技能': 'Skills',
  '连接器': 'Connectors',
  '操控': 'Computer',
  '自动化': 'Automation',
  '设置': 'Settings',
  '就绪': 'Ready',
  '生成中': 'Generating',
  '已连接': 'Connected',
  '连接中': 'Connecting',
  '连接失败': 'Connection failed',
  '最小化': 'Minimize',
  '最大化': 'Maximize',
  '还原': 'Restore',
  '关闭': 'Close',
  '独立 Chat': 'Independent chat',
  '左栏': 'Sidebar',
  '最大化或还原': 'Maximize / Restore',
  '隐藏到托盘': 'Hide to tray',
  '正在重新连接': 'Reconnecting',

  // —— 输入栏 / Composer ——
  // 5 个权限档（对齐 Claude Code）
  '询问权限': 'Ask permissions',
  '每次使用工具前都征求许可': 'Ask before every tool use',
  '接受编辑': 'Accept edits',
  '自动应用文件编辑；运行命令、桌面或联网操作前询问': 'Auto-apply file edits; ask before commands, desktop, or web actions',
  '计划模式': 'Plan mode',
  '只读研究并制定计划，不做任何更改': 'Research read-only and draft a plan without making changes',
  '自动模式': 'Auto mode',
  '自主运行命令与编辑，仅在危险或破坏性操作前询问': 'Run commands and edits autonomously; ask only before dangerous or destructive actions',
  '绕过权限': 'Bypass permissions',
  '不再询问，完全访问文件、命令与网络': 'No more prompts — full access to files, commands, and the network',
  // 旧三档文案（保留兼容）
  '请求批准': 'Ask to approve',
  '编辑外部文件和使用互联网时始终询问': 'Always ask before editing external files or using the internet',
  '替我审批': 'Auto-approve',
  '仅对检测到的风险操作请求批准': 'Only ask for detected risky actions',
  '完全访问权限': 'Full access',
  '完全访问': 'Full access',
  '可不受限制地访问互联网和您电脑上的任何文件': 'Unrestricted access to the internet and any file on your computer',
  '开新对话': 'New chat',
  '压缩上下文，释放空间': 'Compact context to free space',
  '撤销上一轮对话': 'Undo the last turn',
  '无匹配指令': 'No matching command',
  '让 Metis 在这个项目里开始工作...': 'Ask Metis to work in this project...',
  '松开以添加到本次消息': 'Drop to attach to this message',
  '添加附件': 'Attach files',
  '停止生成': 'Stop generating',
  '发送消息': 'Send message',
  '权限状态暂不可用': 'Permission status unavailable',
  '正在解析': 'parsing',
  '解析失败，可移除后重试': 'Parse failed — remove and retry',
  '已截断': 'truncated',

  // —— 启动首屏 / BootOverlay ——
  '后端已就绪': 'Backend ready',
  '后端启动失败': 'Backend failed to start',
  '正在启动 Metis 后端': 'Starting the Metis backend',
  '启动失败，Metis 已尝试自动修复后端环境；下面是诊断信息': 'Startup failed. Metis tried to auto-repair the backend environment; diagnostics are below.',
  '后端日志': 'Backend log',
  '等待启动事件...': 'Waiting for startup events...',
  '重试并重新修复': 'Retry and repair',
  '打开日志': 'Open log',

  // —— 侧栏 / Sidebar ——
  '当前工作区': 'Current workspace',
  '打开文件夹': 'Open folder',
  '新建会话': 'New chat',
  '菜单': 'Menu',
  '清空会话': 'Clear chats',
  '移除工作区': 'Remove workspace',
  '暂无会话': 'No chats yet',
  '重命名会话': 'Rename chat',
  '删除会话': 'Delete chat',
  '会话': 'Chat',
  '条消息': 'messages',
  '搜索会话全文': 'Search chats',
  '继续输入': 'Keep typing',
  '搜索中': 'Searching',
  '个结果': 'results',
  '至少输入 2 个字符。': 'Type at least 2 characters.',
  '搜索中...': 'Searching...',
  '没有结果': 'No results',
  '缓存': 'cache',
  '缓存命中': 'Cache hit',
  '系统提示词': 'System prompt',
  'MCP 工具': 'MCP tools',
  '内置工具': 'Builtin tools',
  '消息': 'Messages',
  '剩余': 'Free',
  '压缩中...': 'Compacting...',
  '压缩上下文': 'Compact context',
  '压缩': 'Compact',
  '上下文偏高，建议压缩后继续长任务。': 'Context is high; compact before continuing long tasks.',
  '正在压缩': 'Compacting',
  '压缩未完成': 'Compaction incomplete',
  '等待后端返回摘要。': 'Waiting for the backend summary.',

  // —— 首启向导 / SetupWizard 步骤 + 供应商名 ——
  '欢迎': 'Welcome',
  '供应商': 'Provider',
  '配置': 'Configure',
  '验证': 'Verify',
  '完成': 'Done',
  '自定义 OpenAI 中转站': 'Custom OpenAI relay',

  // —— 设置：对话 / 工具 / 外观 ——
  '对话设置': 'Chat settings',
  '自动记忆': 'Auto memory',
  '自动创建技能': 'Auto-create skills',
  '全局记忆': 'Global memory',
  '项目记忆': 'Project memory',
  '工具已启用': 'tools enabled',
  '主题与语言': 'Theme & language',
  '字体': 'Font',
  'UI 字号': 'UI size',
  '代码字号': 'Code size',
  '白天': 'Day',
  '夜晚': 'Night',
  '浅色（白天）': 'Light (day)',
  '深色（夜晚）': 'Dark (night)',
  '调整 Metis UI 使用的基础字号，聊天、侧栏、按钮和设置页会一起变大。': 'Adjusts the base UI font size — chat, sidebar, buttons, and settings scale together.',
  '调整代码块、终端、Diff、工具输出和文件预览的基础字号。': 'Adjusts the base font size for code blocks, terminal, diffs, tool output, and file previews.',

  // —— 设置：网络 / 额度 ——
  '代理设置': 'Proxy',
  '给 LLM 请求使用。Clash 常见配置是 HTTP 代理 `127.0.0.1:7890`。': 'Used for LLM requests. A common Clash setup is HTTP proxy `127.0.0.1:7890`.',
  '代理模式': 'Proxy mode',
  '跟随系统 / 环境变量': 'Follow system / env vars',
  '自定义 Clash / HTTP 代理': 'Custom Clash / HTTP proxy',
  '关闭代理': 'Disable proxy',
  '协议': 'Protocol',
  '端口': 'Port',
  '网关 / 主机': 'Gateway / host',
  '绕过地址': 'Bypass list',
  '实际开发提示': 'Practical tips',
  '如果 DeepSeek / OpenAI 中转站不通，优先检查代理模式、Base URL、模型名和 API Key 是否匹配。': 'If the DeepSeek / OpenAI relay is unreachable, first check that proxy mode, Base URL, model name, and API key all match.',
  '关闭代理会让 Metis LLM 请求忽略环境变量和 Windows 系统代理。': 'Disabling the proxy makes Metis LLM requests ignore env vars and the Windows system proxy.',
  '额度 / Usage': 'Usage',
  '未选择模型': 'No model selected',
  '查询中...': 'Loading...',
  '刷新额度': 'Refresh usage',
  '点击刷新后读取供应商只读额度接口；不会发起模型调用。': 'Click refresh to read the provider read-only usage API; no model call is made.',
  '今日请求': "Today's requests",
  '今日 Tokens': "Today's tokens",
  '今日费用': "Today's cost",
  '累计请求': 'Total requests',
  '累计 Tokens': 'Total tokens',
  '累计费用': 'Total cost',
  '读取规则': 'Read rules',
  'PinAI / 自定义 OpenAI 中转站优先读取 `/v1/usage`；DeepSeek 读取 `/user/balance`。': 'PinAI / custom OpenAI relays read `/v1/usage` first; DeepSeek reads `/user/balance`.',
  '如果供应商不开放额度接口，Metis 会显示不支持，不会编造百分比。': 'If the provider exposes no usage API, Metis shows it as unsupported rather than inventing percentages.',

  // —— 设置：关于 ——
  '版本': 'Version',
  '已安装版本': 'Installed build',
  '开发模式': 'Dev mode',
  '开源协议': 'License',
  '项目主页': 'Homepage',
  '仓库链接待发布后补充': 'Repo link to be added after release',
  '更新源': 'Update feed',
  '检查中...': 'Checking...',
  '检查更新': 'Check for updates',
  '发布诊断': 'Release diagnostics',
  '生成不含密钥的诊断包，包含版本、平台、后端日志、工具调用、Preview 错误和截图证据摘要。': 'Generate a secret-free diagnostics bundle with version, platform, backend logs, tool calls, Preview errors, and screenshot evidence summary.',
  '后端状态': 'Backend status',
  '后端端口': 'Backend port',
  '终端后端': 'Terminal backend',
  '数据根': 'Data root',
  'Metis 数据': 'Metis data',
  '等待诊断数据': 'Awaiting diagnostics',
  'Electron 数据': 'Electron data',
  '暂无后端日志。': 'No backend log yet.',
  '刷新诊断': 'Refresh diagnostics',
  '生成中...': 'Generating...',
  '生成诊断包': 'Build diagnostics bundle',

  // —— 设置：终端 ——
  '默认终端': 'Default terminal',
  '配置 Metis 终端卡片和终端入口的新建 Shell。': 'Configure the shell launched by the Metis terminal card and terminal entry.',
  '默认 Shell': 'Default shell',
  'Python 解释器': 'Python interpreter',
  '类似 PyCharm 的解释器选择，指定后端和工具链使用的 Python 环境。': 'PyCharm-style interpreter selection — sets the Python environment used by the backend and toolchain.',
  '已指定': 'Custom',
  '自动检测': 'Auto-detect',
  'Python 路径': 'Python path',
  '自动检测（留空即可）— 也可粘贴 python.exe 完整路径': 'Auto-detect (leave blank) — or paste the full python.exe path',
  '浏览选择 python.exe': 'Browse for python.exe',
  '已保存': 'Saved',
  '确认保存': 'Confirm',
  '保存': 'Save',
  '恢复自动检测': 'Restore auto-detect',
  '当前使用：': 'Currently: ',
  '待确认：': 'Pending: ',
  '（点击「确认保存」生效）': ' (click Confirm to apply)',
  'Anaconda 环境：选择 D:\\Anaconda3\\envs\\环境名\\python.exe': 'Anaconda env: pick D:\\Anaconda3\\envs\\<env>\\python.exe',
  '系统 Python：选择 C:\\Python312\\python.exe 或类似路径': 'System Python: pick C:\\Python312\\python.exe or similar',
  '修改后需要重启 Metis 或点击设置面板「保存」按钮后重启生效。': 'Changes take effect after restarting Metis, or after clicking Save in settings and restarting.',
  '常用场景': 'Common scenarios',
  'npm run dev、git status、python -m pytest 等命令可在底栏终端连续运行。': 'Commands like npm run dev, git status, and python -m pytest can run continuously in the bottom terminal.',

  // —— 设置：桌面 ——
  '桌面操控': 'Desktop control',
  '可用': 'Available',
  '不可用': 'Unavailable',
  '当前模型': 'the current model',
  '可用于视觉桌面任务。': 'can perform vision desktop tasks.',
  '不支持视觉桌面任务。': 'does not support vision desktop tasks.',
  '视觉理解': 'Vision',
  '支持': 'Yes',
  '不支持': 'No',
  '鼠标控制': 'Mouse control',
  '键盘输入': 'Keyboard input',
  '紧急停止': 'Emergency stop',
  '窗口行为': 'Window behavior',
  '关闭窗口': 'Close window',
  '进入托盘': 'Minimize to tray',
  '标题栏': 'Title bar',
  'Electron 原生控制': 'Native Electron controls',
  '本地预览': 'Local preview',
  '右侧工作台': 'Right workbench',

  // —— 设置对话框 ——
  '取消': 'Cancel',
  '保存中...': 'Saving...',
  '删除权限规则？': 'Delete permission rule?',
  '这个工具': 'this tool',
  '删除后，': 'After deletion, ',
  '下次遇到风险操作会重新询问。': 'will ask again on its next risky action.',
  '删除': 'Delete',
  '已取消生成诊断包。': 'Diagnostics bundle canceled.',
  '诊断包已保存: ': 'Diagnostics bundle saved: ',

  // —— 设置：模型 ModelTab ——
  'Provider 配置': 'Provider',
  '修复当前配置': 'Repair config',
  '默认模型': 'Default model',
  '手动填写': 'Manual',
  '本地预设': 'Local presets',
  '个': '',
  '工具调用': 'Tool calling',
  '未知/不支持': 'Unknown / no',
  '本地检查配置': 'Check config locally',
  '探测中...': 'Probing...',
  '深度探测': 'Deep probe',
  '模型选择': 'Model selection',
  '读取中...': 'Loading...',
  '刷新模型目录': 'Refresh model catalog',
  '模型目录': 'Model catalog',
  '个模型': 'models',
  '这个供应商没有返回可切换的聊天模型，仍可手动填写模型名。': 'This provider returned no switchable chat models; you can still enter a model name manually.',
  '非聊天模型': 'non-chat model',
  '模型能力': 'Model capabilities',
  '模型族': 'Model family',
  '视觉': 'Vision',
  '结构化输出': 'Structured output',
  'Metis 隔离后台任务：运行、产物、诊断和验证证据链。': 'Metis isolated background jobs: run, artifacts, diagnostics, and a verification evidence chain.',
  '可用工具数': 'Available tools',
  '上下文窗口': 'Context window',
  '指令遵循': 'Instruction adherence',
  '当前模型不支持视觉，桌面操控需要切换到 Claude、GPT-4o、Gemini 或视觉模型。': 'The current model has no vision; desktop control needs a vision model like Claude, GPT-4o, or Gemini.',
  '正在读取模型能力...': 'Loading model capabilities...',
  '当前模型看起来不属于 ': 'The current model does not seem to belong to ',
  '。建议修复配置，或选择本地预设模型。': '. Repair the config, or pick a local preset model.',
  '基础 tier 已自动裁剪工具集至 ': 'Base tier auto-trimmed the toolset to ',
  ' 个核心工具。': ' core tools.',

  // —— 通知卡片 / NoticeCards ——
  '自学习提示': 'Self-learning notice',
  '已更新记忆': 'Memory updated',
  '关闭学习提示': 'Dismiss learning notice',
  '记忆': 'Memory',
  '查看记忆': 'View memory',
  '查看技能': 'View skills',
  '任务清单更新': 'Task list update',
  '任务清单已更新': 'Task list updated',
  '关闭任务清单提示': 'Dismiss task list notice',
  '总计': 'Total',
  '进行中': 'In progress',
  '长任务恢复提示': 'Long-task recovery',
  '检测到未完成的上次运行': 'Detected an unfinished previous run',
  '工具': 'Tools',
  '上一次运行没有正常结束。': 'The last run did not end cleanly.',
  '中断点: ': 'Checkpoint: ',
  '原需求: ': 'Original request: ',
  '继续执行': 'Resume',
  '继续查看': 'Keep viewing',
  '标记失败': 'Mark failed',
  '清理状态': 'Clear state',
  '第 ': 'Turn ',
  ' 轮': '',
  ' 步': ' steps',
  '上下文整理中': 'Organizing context',
  '正在整理上下文': 'Organizing context',
  '收束历史消息，保留关键线索': 'Condensing history, keeping key clues',

  // —— 消息气泡 / MessageBubble ——
  '不支持预览此 HTML 文件': 'This HTML file cannot be previewed',
  '无法预览文件': 'Cannot preview file',
  '在右栏打开链接？': 'Open link in the right rail?',
  '确认后会在 Metis 右侧预览栏打开这个网页。': 'Confirming opens this page in the Metis right preview rail.',
  '打开链接': 'Open link',
  '复制回复': 'Copy reply',
  '已复制': 'Copied',
  '复制': 'Copy',
  '回到这里': 'Rewind here',
  '附件': 'Attachments',
  '已压缩上下文': 'Context compacted',
  '此线以上的内容模型不再逐条读取': 'The model no longer reads content above this line item by item',
  '条': 'items',
  '上下文已整理': 'Context organized',
  '关闭上下文整理提示': 'Dismiss context notice',
  '压缩后的项目摘要': 'Compacted project summary',
  '收起上下文整理提示': 'Collapse context notice',

  // —— 子代理 / SubagentGroup ——
  '子代理并行状态': 'Parallel subagents status',
  '并行子代理': 'Parallel subagents',
  '运行中': 'Running',
  '错误': 'Error',
  '活动': 'Activity',
  '隐藏子代理状态': 'Hide subagent status',
  '暂无子代理活动': 'No subagent activity yet',
  '并行子代理启动后会在这里显示每个任务的进度和结果。': 'When parallel subagents run, each task’s progress and result appear here.',
  '子代理活动': 'Subagent activity',
  '等待子代理输出': 'Waiting for subagent output',
  '右栏查看': 'View in right rail',
  '整体进度': 'Overall progress',
  '研究': 'Research',
  '实现': 'Implementation',

  // —— 工具活动 / ToolCallBlock ——
  '工具活动': 'Tool activity',
  '全部展开': 'Expand all',
  '全部收起': 'Collapse all',
  '待确认': 'Awaiting approval',
  '详情': 'Details',
  '变更': 'Changes',
  '工具 Diff 摘要': 'Tool diff summary',
  '另有 ': 'Plus ',
  ' 行，打开右栏 Diff 查看完整内容。': ' more lines — open the right-rail diff for the full content.',
  '等待工具事件': 'Waiting for tool events',
  '暂无工具': 'No tools',
  '步骤': 'Step',
  '报告活动': 'Report activity',
  '步': 'steps',
  '个产物': 'artifacts',
  '正在执行 ': 'Running ',
  ' 个工具': ' tools',
  ' 个工具失败': ' tools failed',

  // —— 右栏工作台 / RightRail ——
  'Preview 加载失败': 'Preview failed to load',
  '只支持 http://、https:// 或本工作区 HTML 文件': 'Only http://, https://, or workspace HTML files are supported',
  '外部打开被安全策略拦截': 'External open blocked by security policy',
  '当前工作区没有可预览文件。': 'No previewable files in this workspace.',
  '后端连接后会自动加载工作区文件。': 'Workspace files load automatically once the backend connects.',
  '选择文件后在这里预览。': 'Select a file to preview it here.',
  '文件较大，已显示前半部分。': 'Large file — showing the first half.',
  '文件过大，已省略内容。': 'File too large — content omitted.',
  '当前会话暂无运行时画像。': 'No runtime profile for this session yet.',
  '长任务正在运行': 'Long task is running',
  '长任务模式已授权': 'Long-task mode is authorized',
  '后台主动性保持手动开启': 'Background autonomy remains opt-in',
  '需权限': 'Needs permission',
  '新鲜验收': 'Fresh verification',
  '后台可用': 'Background ready',
  '需手动开启': 'Opt-in required',
  '有错误': 'Has errors',
  '等待下一步任务。': 'Waiting for the next task.',
  '二进制文件暂不预览': 'Binary files are not previewed',
  '可以通过工具读取或在系统文件管理器中打开。': 'Read it via a tool or open it in the system file manager.',
  '工具输出': 'Tool output',
  ' 行': ' lines',
  ' 字符': ' chars',
  '暂无工具输出': 'No tool output',
  '点击聊天里的工具卡片可在这里查看完整结果。': 'Click a tool card in the chat to view the full result here.',
  '文件变更列表': 'File change list',
  ' 个文件': ' files',
  '已撤销': 'Reverted',
  '文件变更 Diff': 'File change diff',
  '暂无文件变更': 'No file changes',
  '运行写入、编辑或删除文件的工具后，这里会显示 Diff。': 'After tools write, edit, or delete files, the diff appears here.',
  '网页标签页': 'Web tabs',
  '前端预览': 'Frontend preview',
  '当前工作区未识别到可启动的前端项目': 'No startable frontend project detected in this workspace',
  '识别当前工作区并打开本地预览': 'Detect this workspace and open local preview',
  '启动': 'Start',
  '停止': 'Stop',
  '验收': 'Audit',
  '验收通过': 'Audit passed',
  '需要复查': 'Needs review',
  '验收失败': 'Audit failed',
  '网页导航': 'Web navigation',
  '后退': 'Back',
  '前进': 'Forward',
  '停止加载': 'Stop loading',
  '刷新': 'Refresh',
  '页面缩放': 'Page zoom',
  '缩小页面': 'Zoom out',
  '放大页面': 'Zoom in',
  '当前 ': 'Current ',
  ' · 点击恢复 100%': ' · click to reset to 100%',
  '当前页面缩放 ': 'Current zoom ',
  '，点击恢复 100%': ', click to reset to 100%',
  '更多网页操作': 'More web actions',
  '启动中': 'Starting',
  '启动预览': 'Start preview',
  '停止预览': 'Stop preview',
  '验收中': 'Auditing',
  '视觉验收': 'Visual audit',
  '收起详情': 'Hide details',
  '查看详情': 'View details',
  '展开详情': 'Show details',
  '系统浏览器打开': 'Open in system browser',
  '网页控制栏': 'Web controls',
  '正在加载 ': 'Loading ',
  '网页预览': 'Web preview',
  '输入 URL 或点击聊天中的链接，在右栏并排查看。': 'Enter a URL or click a link in the chat to view it side by side.',
  '任务清单': 'Task list',
  '任务 ': 'Task ',
  '任务清单：智能体规划任务后，这里实时显示进度——完成打钩、进行中转圈、待办空心圆。': 'Task list: once the agent plans tasks, progress updates live here — done checked, in-progress spinning, todo hollow.',
  '关闭 ': 'Close ',
  '后台任务中心': 'Background tasks',
  '后台运行': 'Background runs',
  '最近任务': 'recent tasks',
  '刷新后台任务': 'Refresh background tasks',
  '后端连接后显示后台任务。': 'Background tasks show once the backend connects.',
  '暂无后台任务。': 'No background tasks.',
  '运行中任务': 'Running tasks',
  '跳转到会话': 'Jump to chat',
  '刚刚': 'just now',
  '取消中': 'Canceling',
  '排队': 'Queued',
  '失败': 'Failed',
  '已取消': 'Canceled',
  '未知': 'Unknown',
  '已识别': 'Detected',
  '已停止': 'Stopped',
  '待识别': 'Not detected',
  '网页': 'Web page',
  '新增': 'Added',
  '修改': 'Modified',
  '冲突': 'Conflict',
  '已拦截': 'Blocked',
  '待处理': 'Pending',

  // —— 二级页面 / Sections (技能/MCP/电脑) ——
  '加载中': 'Loading',
  '读取失败': 'Load failed',
  '重试': 'Retry',
  '是': 'Yes',
  '否': 'No',
  '个技能': 'skills',
  '自学习': 'Self-learning',
  '复杂任务完成后，Metis 会把可复用经验沉淀到本地记忆和技能。': 'After complex tasks, Metis distills reusable experience into local memory and skills.',
  '自动记忆开': 'Auto memory on',
  '自动记忆关': 'Auto memory off',
  '自动技能开': 'Auto skills on',
  '自动技能关': 'Auto skills off',
  '第三方连接器使用标准 OAuth，token 仅在本机加密保存。': 'Third-party connectors use standard OAuth; tokens are encrypted and stored only on this machine.',
  '刷新状态': 'Refresh status',
  '当前系统暂不可用安全加密存储。': 'Secure encrypted storage is not available on this system.',
  '已断开连接器': 'Connector disconnected',
  '连接器操作失败': 'Connector action failed',
  'Token 环境变量': 'Token environment variable',
  'Personal access token（可选）': 'Personal access token (optional)',
  '本地测试 token（可选）': 'Local test token (optional)',
  '留空则尝试 OAuth': 'Leave empty to try OAuth',
  '连接中...': 'Connecting...',
  'OAuth 连接': 'Connect with OAuth',
  '加密保存 token': 'Encrypt and save token',
  'Gmail 敏感 scope 公开分发前需要 Google OAuth 验证；测试模式需添加测试用户。': 'Gmail sensitive scopes require Google OAuth verification before public distribution; test mode needs explicit test users.',
  '缺少 OAuth client id。': 'Missing OAuth client id.',
  '内置': 'Builtin',
  '全局': 'Global',
  '项目': 'Project',
  '已启用': 'Enabled',
  '粘贴包含 SKILL.md 的目录路径': 'Paste a directory path containing SKILL.md',
  '导入': 'Import',
  '选择目录': 'Choose folder',
  '暂无本地技能': 'No local skills',
  '完成复杂任务后可沉淀为 SKILL.md。': 'Complex tasks can be distilled into a SKILL.md.',
  '内置技能': 'Builtin skills',
  '全局技能': 'Global skills',
  '项目技能': 'Project skills',
  '项目覆盖': 'Project override',
  '仅手动': 'Manual only',
  '模型可触发': 'Model-invocable',
  '后台技能': 'Background skill',
  '查看': 'View',
  '启用': 'Enabled',
  '停用': 'Disabled',
  '删除中': 'Deleting',
  '删除本地技能？': 'Delete local skill?',
  '会删除对应的 SKILL.md 目录。': 'This deletes the corresponding SKILL.md directory.',
  '此操作不能撤销。': 'This cannot be undone.',
  '选择一个技能': 'Select a skill',
  '查看、编辑或停用自动沉淀的 SKILL.md。': 'View, edit, or disable an auto-distilled SKILL.md.',
  '仅手动触发': 'Manual trigger only',
  '模型可自动触发': 'Model auto-trigger',
  '打开目录': 'Open folder',
  '保存中': 'Saving',
  '无法打开目录: ': 'Cannot open folder: ',
  'MCP 可用': 'MCP available',
  '已禁用': 'Disabled',
  '重载中...': 'Reloading...',
  '热重载 MCP': 'Hot-reload MCP',
  '暂无 MCP server': 'No MCP servers',
  '检测到配置后会显示连接状态。': 'Connection status shows once a config is detected.',
  '未配置启动方式': 'No launch method configured',
  '健康': 'Healthy',
  '异常': 'Unhealthy',
  '未连接': 'Disconnected',
  '重连': 'Reconnect',
  '断开': 'Disconnect',
  '配置来源': 'Config sources',
  '未发现配置文件': 'No config files found',
  '桌面自动化模块不可用': 'Desktop automation module unavailable',
  '安全总开关': 'Master switch',
  '开': 'On',
  '关': 'Off',
  '执行模式': 'Exec mode',
  '视觉步骤': 'Vision steps',
  '视觉模型': 'Vision model',
  '安全控制': 'Safety controls',
  '关闭操控': 'Disable control',
  '启用操控': 'Enable control',
  '暂停': 'Pause',
  '恢复': 'Resume',
  '运行状态': 'Run status',
  '最近日志': 'Recent log',
  ' 不支持视觉功能，无法启用桌面操控。': ' has no vision support; desktop control cannot be enabled.',
  '已关闭': 'Closed',

  // —— 定时任务 / CronPanel ——
  '每分钟': 'Every minute',
  '每 30 分钟': 'Every 30 minutes',
  '每天 09:00': 'Daily 09:00',
  '每天 18:00': 'Daily 18:00',
  '定时运行 prompt，结果会保存成会话。': 'Run prompts on a schedule; results are saved as chats.',
  '任务': 'Tasks',
  '最近运行': 'Last run',
  '下次运行': 'Next run',
  '任务名称': 'Task name',
  '要定时执行的任务 prompt': 'Prompt to run on schedule',
  '保存修改': 'Save changes',
  '新建任务': 'New task',
  '取消编辑': 'Cancel edit',
  '暂无定时任务': 'No scheduled tasks',
  '创建一个任务后，Metis 会按计划运行并保存结果会话。': 'After you create a task, Metis runs it on schedule and saves the result chat.',
  '下次 ': 'Next ',
  ' · 上次 ': ' · last ',
  '编辑': 'Edit',
  '运行': 'Run',
  '上次结果': 'Last result',
  '删除定时任务？': 'Delete scheduled task?',
  '计划: ': 'Schedule: ',
  '提示词: ': 'Prompt: ',
  '删除后不会再按计划运行。': 'It will no longer run on schedule after deletion.',
  '未设置': 'Not set',
  '未安排': 'Not scheduled',

  // —— 独立对话 / SideChatPanel ——
  '独立上下文，不读取智能体任务、工具或工作区历史': 'Independent context — does not read agent tasks, tools, or workspace history',
  '独立 Chat Dock': 'Independent chat dock',
  '独立 Chat 历史': 'Independent chat history',
  'Chat 历史': 'Chat history',
  ' 条独立会话': ' independent chats',
  '收起历史': 'Collapse history',
  '展开历史': 'Expand history',
  '新建独立 Chat': 'New independent chat',
  '重命名': 'Rename',
  '调整 Chat 历史高度': 'Resize chat history height',
  '拖动调整 Chat 上下区域高度': 'Drag to resize chat sections',
  '独立上下文': 'Independent context',
  '清空当前 Chat': 'Clear this chat',
  '收起 Chat': 'Collapse chat',
  '右栏之外的独立聊天': 'A separate chat outside the right rail',
  '适合解释概念、拆想法、闲聊；不会污染智能体上下文。': "Great for explaining concepts, brainstorming, or chatting — it won't pollute the agent context.",
  '接收中': 'Receiving',
  '独立 Chat 输入': 'Independent chat input',
  '问一个不会污染智能体上下文的问题...': "Ask something that won't pollute the agent context...",
  '发送': 'Send',

  // —— 设置共享数据/函数 settingsShared (字体/Shell/权限) ——
  '官方 Sans': 'Official Sans',
  'Metis 默认字体栈，英文和中文都优先保证清晰。': 'Metis default font stack — clear for both English and Chinese.',
  '系统默认': 'System default',
  '跟随 Windows / 系统 UI 字体。': 'Follows the Windows / system UI font.',
  '微软雅黑': 'Microsoft YaHei',
  '中文界面更熟悉，适合长时间阅读。': 'Familiar for Chinese UI, good for long reading.',
  '更接近现代开发工具的英文显示。': 'Closer to modern dev-tool English rendering.',
  'Windows 默认推荐，适合 npm、Python、Git 等日常命令。': 'Recommended default on Windows — good for npm, Python, Git.',
  '传统 Windows 命令解释器。': 'Traditional Windows command interpreter.',
  'Git Bash、WSL 或 PATH 中可用的 bash。': 'bash from Git Bash, WSL, or PATH.',
  'POSIX sh，适合轻量脚本命令。': 'POSIX sh — good for lightweight scripts.',
  '系统 Shell': 'System shell',
  'Windows 走 ComSpec，macOS/Linux 走 SHELL 环境变量。': 'Uses ComSpec on Windows, SHELL on macOS/Linux.',
  '写入前确认': 'Confirm before write',
  '删除前确认': 'Confirm before delete',
  '拒绝环境密钥': 'Deny env secrets',
  '总是允许': 'Always allow',
  '总是拒绝': 'Always deny',
  '每次询问': 'Always ask',
  '策略模板': 'Policy template',
  '输入框快捷权限': 'Composer quick permission',
  '审批弹窗': 'Approval dialog',
  '手动规则': 'Manual rule',
  '全部参数': 'All args',
  '高风险': 'High risk',
  '可能删除、运行命令或改变系统状态': 'May delete, run commands, or change system state',
  '需复核': 'Needs review',
  '可能修改工作区内容': 'May modify workspace content',
  '低风险': 'Low risk',
  '通常是读取或查询类工具': 'Usually read or query tools',

  // —— 权限面板 / PermissionPanel ——
  '权限中心': 'Permissions',
  '管理当前工作区的工具放行、拒绝、询问规则和最近审批记录。': 'Manage tool allow/deny/ask rules and recent approvals for this workspace.',
  '保存规则': 'Saved rules',
  '最近审批': 'Recent approvals',
  '拒绝规则': 'Deny rules',
  '规则文件': 'Rules file',
  '等待后端返回': 'Waiting for backend',
  '审计日志': 'Audit log',
  '授权目录': 'Writable roots',
  '全工具访问不等于全盘写入；桌面、文档等工作区外目录需要在这里单独授权。': 'Full tool access is not whole-disk write access; Desktop, Documents, and other outside-workspace folders must be authorized here.',
  '添加目录': 'Add folder',
  '添加桌面': 'Add Desktop',
  '添加文档': 'Add Documents',
  '添加下载': 'Add Downloads',
  '尚未授权工作区外可写目录。': 'No outside-workspace writable folders are authorized yet.',
  '删除授权目录？': 'Delete writable folder?',
  '删除后，Metis 不能再写入该工作区外目录。': 'After deletion, Metis can no longer write to that outside-workspace folder.',
  '一键添加常见的路径级工具策略，适合真实项目开发时先收紧风险。': 'One-click common path-level tool policies — good for tightening risk early in real projects.',
  '搜索': 'Search',
  '工具、目录、会话或来源': 'Tool, directory, chat, or source',
  '权限动作筛选': 'Permission action filter',
  '全部': 'All',
  '选择当前列表': 'Select current list',
  ' 已选择': ' selected',
  '批量删除': 'Bulk delete',
  '清理冲突': 'Clean up conflicts',
  '导入 / 导出': 'Import / Export',
  '导出内容只包含工具、动作、参数匹配和来源，不包含 API Key、审计详情或聊天内容。': 'Export includes only tool, action, arg match, and source — no API keys, audit details, or chat content.',
  '导出 JSON': 'Export JSON',
  '点击导出当前规则': 'Click to export current rules',
  '导出规则': 'Export rules',
  '导入 JSON': 'Import JSON',
  '导入规则': 'Import rules',
  '手动添加规则': 'Add rule manually',
  '可选填写参数模式，例如 `path = src/*`，用于路径级放行、拒绝或询问。': 'Optionally add an arg pattern like `path = src/*` for path-level allow/deny/ask.',
  '添加中...': 'Adding...',
  '添加规则': 'Add rule',
  '已保存规则': 'Saved rules',
  '没有匹配的保存规则。遇到危险工具时可以在确认弹窗里选择记住，也可以手动添加。': 'No matching saved rules. When a risky tool appears, choose Remember in the dialog, or add one manually.',
  '选择 ': 'Select ',
  '范围 · ': 'Scope · ',
  '来源 · ': 'Source · ',
  '没有匹配的审批记录。': 'No matching approval records.',
  '允许': 'Allowed',
  '拒绝': 'Denied',
  ' · 已记住 ': ' · remembered ',
  '批量删除权限规则？': 'Bulk delete permission rules?',
  '将删除 ': 'Will delete ',
  '将导入 ': 'Will import ',
  ' 条已选择的权限规则。': ' selected permission rules.',
  '删除所选': 'Delete selected',
  '导入权限规则？': 'Import permission rules?',
  ' 条权限规则。': ' permission rules.',
  '没有发现可导入的权限规则。': 'No importable permission rules found.',
  '已导入 ': 'Imported ',
  ' 条规则。': ' rules.',
  '清理冲突权限规则？': 'Clean up conflicting rules?',
  ' 条重复或冲突的旧规则，保留每个工具范围里最新的一条。': ' duplicate/conflicting old rules; the newest per tool scope is kept.',

  // —— 供应商管理 / ProviderRegistryManager ——
  '供应商管理': 'Provider management',
  '添加自定义供应商（内网中转、新模型）无需改代码。密钥只填环境变量名（不存明文）。': 'Add custom providers (internal relays, new models) without editing code. Keys are stored as env-var names only (never plaintext).',
  '加载中…': 'Loading…',
  '自定义': 'Custom',
  '并行': 'Parallel',
  '探测模型与能力': 'Probe models & capabilities',
  '删除供应商': 'Delete provider',
  '供应商 ID': 'Provider ID',
  '显示名': 'Display name',
  'API Key 环境变量名': 'API key env var',
  '临时 API Key（仅探测）': 'Temp API key (probe only)',
  '模型列表（逗号分隔）': 'Models (comma-separated)',
  '支持视觉 / computer use': 'Supports vision / computer use',
  '支持并行工具调用': 'Supports parallel tool calls',
  '探测中…': 'Probing…',
  '探测': 'Probe',
  '保存中…': 'Saving…',
  '保存供应商': 'Save provider',
  '新增供应商': 'Add provider',
  '供应商 ID 和 Base URL 必填': 'Provider ID and Base URL are required',
  '保存失败': 'Save failed',
  '删除失败': 'Delete failed',
  '探测失败': 'Probe failed',
  '保存失败，无法探测': 'Save failed; cannot probe',

  // —— 后端面向用户的消息(供应商校验/模型目录/额度，前端 t() 翻译；动态串原样回退) ——
  '深度探测完成': 'Deep probe complete',
  '配置检查通过，provider 一致性探测已完成。': 'Config check passed; provider consistency probe complete.',
  '探测结果已落盘，运行时会优先使用该模型的实测能力。': "Probe results saved; runtime prefers this model's measured capabilities.",
  '深度探测未完成，运行时将回退到保守 provider profile。': 'Deep probe incomplete; runtime falls back to a conservative provider profile.',
  '配置通过，深度探测失败': 'Config OK, deep probe failed',
  '本地配置有效，但真实小请求探测未完成。': 'Local config is valid, but the live probe request did not complete.',
  '请检查网络、余额、模型权限或中转站协议兼容性。': 'Check network, balance, model permissions, or relay protocol compatibility.',
  '当前供应商不支持远程模型目录，已显示本地预设模型。': 'This provider has no remote model catalog; local preset models are shown.',
  '可以选择预设模型，也可以继续手动填写模型名。': 'Pick a preset model, or keep entering a model name manually.',
  '当前供应商不支持 OpenAI-compatible /models 目录查询。': 'This provider does not support OpenAI-compatible /models catalog queries.',
  '可以继续手动填写模型名。': 'You can keep entering a model name manually.',
  '尚未填写 API Key，已显示本地预设模型。': 'No API key yet; local preset models are shown.',
  '填入 API Key 后可再刷新远程模型目录；未保存的 Key 不会被持久化。': 'Enter an API key to refresh the remote catalog; unsaved keys are not persisted.',
  '查询模型目录需要 API Key。': 'Querying the model catalog requires an API key.',
  '填入 API Key 后再刷新；不会保存未点击保存的 Key。': 'Enter an API key, then refresh; unsaved keys are not stored.',
  '远程模型目录不可用，已使用本地预设模型。': 'Remote model catalog unavailable; local presets used.',
  '请检查 Base URL、API Key、代理和模型平台分组。': 'Check Base URL, API key, proxy, and model platform grouping.',
  '远程模型目录为空，已使用本地预设模型。': 'Remote model catalog is empty; local presets used.',
  '选择一个模型会写入当前设置；也可以继续手动填写。': 'Selecting a model writes it to settings; you can also enter one manually.',
  '查询额度需要 API Key。': 'Querying usage requires an API key.',
  '当前供应商没有已知的只读额度接口。': 'This provider has no known read-only usage API.',
  '模型仍可使用；额度需要到供应商后台查看。': 'The model still works; check usage in the provider console.',
  '请检查 Base URL、API Key、余额接口权限和代理设置。': 'Check Base URL, API key, balance API permissions, and proxy.',
  '选择一个模型会写入当前设置；Ollama 不需要 API Key。': 'Selecting a model writes it to settings; Ollama needs no API key.',
  'Ollama 正在运行，但尚未发现已安装模型。': 'Ollama is running but no installed models were found.',
  '可以先运行 ollama pull <model>，或手动填写已有模型名。': 'Run `ollama pull <model>` first, or enter an existing model name.',
  '未检测到 Ollama 本地服务。': 'No local Ollama service detected.',
  '启动 Ollama 后刷新；也可以继续手动填写模型名。': 'Start Ollama and refresh, or keep entering a model name manually.',
  'DeepSeek 余额可用。': 'DeepSeek balance available.',
  'DeepSeek 余额不可用。': 'DeepSeek balance unavailable.',
  '这里只读取余额，不会发起模型调用。': 'This only reads the balance; no model call is made.',
  '额度查询成功。': 'Usage query succeeded.',
  '额度不可用。': 'Usage unavailable.',
  '钱包余额模式不伪造百分比，只显示金额和单位。': 'Wallet-balance mode shows amount and unit only — no fabricated percentages.',
};
