"""Declarative provider profiles for Metis.

This module mirrors the useful shape of Hermes provider profiles while keeping
Metis' first migration step small and offline.
"""

from __future__ import annotations

from .provider_contract import ProviderId, ProviderProfile


# DeepSeek legacy model note:
# deepseek-chat and deepseek-reasoner are deprecated at Beijing time
# 2026-07-24 23:59, but remain listed for compatibility during migration.
BUILTIN_PROVIDER_PROFILES: tuple[ProviderProfile, ...] = (
    ProviderProfile(
        provider_id=ProviderId("fake"),
        display_name="Fake Provider",
        backend_type="fake",
        aliases=("test", "offline"),
        default_model="fake-model",
        api_key_required=False,
        supports_stream=False,
        supports_tools=False,
    ),
    ProviderProfile(
        provider_id=ProviderId("deepseek"),
        display_name="DeepSeek",
        backend_type="openai",
        aliases=("ds", "deepseek-chat", "deepseek-reasoner"),
        base_url="https://api.deepseek.com",
        default_model="deepseek-v4-flash",
        fallback_models=(
            "deepseek-v4-flash",
            "deepseek-v4-pro",
            "deepseek-chat",
            "deepseek-reasoner",
        ),
        model_context_windows={
            "deepseek-v4-flash": 1_000_000,
            "deepseek-v4-pro": 1_000_000,
            "deepseek-chat": 128_000,
            "deepseek-reasoner": 64_000,
        },
        model_notes={
            "deepseek-chat": "Deprecated at Beijing time 2026-07-24 23:59; use deepseek-v4-flash.",
            "deepseek-reasoner": "Deprecated at Beijing time 2026-07-24 23:59; use deepseek-v4-pro.",
        },
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=True,
        requires_reasoning_passback=True,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("openai"),
        display_name="OpenAI",
        backend_type="openai",
        aliases=("oai",),
        base_url="https://api.openai.com/v1",
        default_model="gpt-4o-mini",
        fallback_models=("gpt-4o-mini", "gpt-4o", "gpt-4.1-mini"),
        model_context_windows={
            "gpt-4o-mini": 128_000,
            "gpt-4o": 128_000,
            "gpt-4.1-mini": 1_047_576,
            "gpt-4.1": 1_047_576,
        },
        supports_stream=True,
        supports_tools=True,
        supports_vision=True,
        parallel_tool_calls=True,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("openai-compatible"),
        display_name="OpenAI Compatible",
        backend_type="openai",
        aliases=("openai_compat",),
        default_model="",
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("custom-openai"),
        display_name="自定义 OpenAI 中转站",
        backend_type="openai",
        aliases=("custom", "custom-openai", "openai-relay", "relay-openai"),
        default_model="",
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("kimi"),
        display_name="Kimi",
        backend_type="openai",
        aliases=("moonshot", "moonshotai"),
        base_url="https://api.moonshot.cn/v1",
        default_model="kimi-k2.6",
        fallback_models=("kimi-k2.6",),
        model_context_windows={"kimi-k2.6": 262_144},
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("zhipu-glm"),
        display_name="Zhipu GLM",
        backend_type="openai",
        aliases=("glm", "zhipu", "bigmodel"),
        base_url="https://open.bigmodel.cn/api/coding/paas/v4",
        default_model="glm-5.1",
        fallback_models=("glm-5.1",),
        model_context_windows={"glm-5.1": 200_000},
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("bailian"),
        display_name="Bailian / Qwen",
        backend_type="openai",
        aliases=("qwen", "dashscope", "aliyun-bailian"),
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        default_model="qwen3-coder-plus",
        fallback_models=("qwen3-coder-plus", "qwen3-max"),
        model_context_windows={
            "qwen3-coder-plus": 1_000_000,
            "qwen3-max": 262_144,
        },
        supports_stream=True,
        supports_tools=True,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("doubao"),
        display_name="Doubao / Volcengine Ark",
        backend_type="openai",
        aliases=("volcengine", "ark", "volces", "byteplus"),
        base_url="https://ark.cn-beijing.volces.com/api/v3",
        default_model="",
        fallback_models=(),
        supports_stream=True,
        supports_tools=True,
        supports_vision=True,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("ollama"),
        display_name="Ollama (Local)",
        backend_type="openai",
        aliases=("local-ollama", "ollama-local"),
        base_url="http://localhost:11434/v1",
        default_model="qwen2.5:7b",
        fallback_models=(),
        api_key_required=False,
        supports_stream=True,
        supports_tools=False,
        supports_vision=False,
        parallel_tool_calls=False,
        openai_compatible=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("anthropic"),
        display_name="Anthropic",
        backend_type="anthropic",
        aliases=("claude",),
        default_model="claude-sonnet-4-20250514",
        fallback_models=("claude-sonnet-4-20250514", "claude-3-5-haiku-latest"),
        model_context_windows={
            "claude-sonnet-4-20250514": 200_000,
            "claude-3-5-haiku-latest": 200_000,
        },
        supports_stream=True,
        supports_tools=True,
        supports_vision=True,
        parallel_tool_calls=True,
    ),
    ProviderProfile(
        provider_id=ProviderId("gemini"),
        display_name="Gemini",
        backend_type="gemini",
        aliases=("google",),
        default_model="gemini-2.0-flash",
        fallback_models=("gemini-2.0-flash", "gemini-1.5-pro"),
        model_context_windows={
            "gemini-2.0-flash": 1_000_000,
            "gemini-1.5-pro": 2_000_000,
        },
        supports_stream=True,
        supports_tools=True,
        supports_vision=True,
        parallel_tool_calls=True,
    ),
)


def builtin_provider_profiles() -> tuple[ProviderProfile, ...]:
    return BUILTIN_PROVIDER_PROFILES
